install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

after_build:
  - npm install -g forever
  - forever start ./lib/app.js
  - forever start ./lib/ui.js
  - ps: dir
  - ps: get-process -name node

test_script:
  # run tests
  - ps: cd test\e2e
  - npm install nightwatch -g --save-dev
  - npm install jdk -g --save-dev
  - node nightwatch -t .\e2e\smoketest.js
  - ps: get-process -name node
  - ps: stop-process -name node
