install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

after_build:
  - npm install -g forever
  - forever start ./lib/app.js 
  - forever start ./lib/ui.js 
  - ps: get-process -name node

test_script:
  # run tests
  - ps: cd .\test\e2e\
  - npm install jdk -g --save-dev
  - npm install 
  - node nightwatch
  - ps: get-process -name node
  - ps: stop-process -name node
  - ps:
        $testResultsFile = ".\reports\*.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }