install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

test_script:
  # run tests
  - npm run lunchsdk
  - npm run lunchui
  - cd test\e2e
  - npm install nightwatch -g --save-dev
  - npm install jdk -g --save-dev
  - node nightwatch -t .\e2e\smoketest.js
