install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

after_build:
  - npm install -g forever
  - forever start ./lib/app.js 
  - forever start ./lib/ui.js 
  - ps: get-process -name node

before_test:
  - ps: cd .\test\e2e\
  - npm install jdk -g --save-dev
  - npm install 

test_script:
  # run tests
  - node nightwatch

on_failure:
  - ps: get-process -name node
  - ps: stop-process -name node
  - ps:
      {
          $testReportPath = .\reports\smoketest.xml
          if([System.IO.File]::Exists($testReportPath)){
              $wc = New-Object 'System.Net.WebClient'
              $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testReportPath))
            }
      }

  notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
      - 'v-maenr@microsoft.com'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
    subject: 'Build {{status}}'                 
    message:
    "<div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
    {{#passed}}
    <h1 style="font-size: 150%;font-weight:normal; color:#078DC7;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} completed</a></h1>{{/passed}}
    {{#failed}}
    <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
    <p style="color: gray">
        Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
        <br />
        <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
    </p>
    <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
     </div>"