install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

test_script:
  # run tests
    - "start cmd.exe @cmd /k \"node ./lib/app.js && exit 1\""
    - "start cmd.exe @cmd /k \"node ./lib/ui.js && exit 1\"" 
    - cd test\e2e
    - npm install nightwatch -g --save-dev
    - npm install jdk -g --save-dev
    - node nightwatch -t .\e2e\smoketest.js
